# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/farmacia
spring.datasource.username=postgres
spring.datasource.password=wirt050706

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# JWT (clave secreta y tiempo de expiración)
jwt.secret=miClaveSecretaSuperSeguraQueDebeSerLarga1234567890
jwt.expiration=86400000