spring.application.name=sanidad-backend
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.secret=claveSecretaParaFarmaciaSanidad2024ConLongitudSuficiente
jwt.expiration=86400000
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=false
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=0
logging.level.org.springframework.security=DEBUG
logging.level.com.farmacia.sanidadbackend=DEBUG
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=1400000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=10