spring.application.name=sanidad-backend
# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/FarmaciaSanidad
spring.datasource.username=postgres
spring.datasource.password=wirt050706
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuración del puerto del servidor (opcional)
server.port=8080

jwt.secret=claveSecretaParaFarmaciaSanidad2024ConLongitudSuficiente
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.com.farmacia.sanidadbackend=DEBUG
